In [1]:
import numpy as np
from IPython import embed
from statsmodels.tsa.arima.model import ARIMA


class ARIMAModel:
    def __init__(self, anomaly_ts_num: float = 0.5):
        self.anomaly_ts_num = anomaly_ts_num
        self.diff_upper_threshold_list = []

    def _arima_model(self, ts):
        assert len(ts.shape) == 1, 'Only support 1-d time series currently'
        ar_result = np.zeros(ts.shape)
        model = ARIMA(ts, order=(2, 0, 0))
        model_fit = model.fit()
        fittedLen = model_fit.fittedvalues.shape[0]
        ar_result[ts.shape[0] - fittedLen:] = model_fit.fittedvalues
        ar_result[:ts.shape[0] - fittedLen] = ts[:ts.shape[0] - fittedLen]
        return ar_result


In [13]:
train_data = np.ones(50)
train_data[20] = 100

test_data = np.ones(50)
test_data[40] = 100

In [14]:
train_data

array([  1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1., 100.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.])

In [15]:
test_data

array([  1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1., 100.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.])

In [7]:
from pyod.models.iforest import IForest

In [16]:
od = IForest(n_estimators=10)

In [17]:
od.fit(train_data.reshape(-1, 1))

IForest(behaviour='old', bootstrap=False, contamination=0.1, max_features=1.0,
    max_samples='auto', n_estimators=10, n_jobs=1, random_state=None,
    verbose=0)

In [18]:
anomaly_score = od.decision_function(test_data.reshape(-1, 1))

In [19]:
anomaly_score

array([-0.        , -0.        , -0.        , -0.        , -0.        ,
       -0.        , -0.        , -0.        , -0.        , -0.        ,
       -0.        , -0.        , -0.        , -0.        , -0.        ,
       -0.        , -0.        , -0.        , -0.        , -0.        ,
       -0.        , -0.        , -0.        , -0.        , -0.        ,
       -0.        , -0.        , -0.        , -0.        , -0.        ,
       -0.        , -0.        , -0.        , -0.        , -0.        ,
       -0.        , -0.        , -0.        , -0.        , -0.        ,
        0.45089951, -0.        , -0.        , -0.        , -0.        ,
       -0.        , -0.        , -0.        , -0.        , -0.        ])

In [20]:
test_data

array([  1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1., 100.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.])

In [22]:
newData = train_data.copy()

In [28]:
newData

array([  1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1., 100.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.])

In [26]:
train_data[10] = -100

In [27]:
train_data

array([   1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
          1., -100.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
          1.,    1.,  100.,    1.,    1.,    1.,    1.,    1.,    1.,
          1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
          1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
          1.,    1.,    1.,    1.,    1.])