In [1]:
import numpy as np
from IPython import embed
from statsmodels.tsa.arima.model import ARIMA


class ARIMAModel:
    def __init__(self, anomaly_ts_num: float = 0.5):
        self.anomaly_ts_num = anomaly_ts_num
        self.diff_upper_threshold_list = []

    def _arima_model(self, ts):
        assert len(ts.shape) == 1, 'Only support 1-d time series currently'
        ar_result = np.zeros(ts.shape)
        model = ARIMA(ts, order=(2, 0, 0))
        model_fit = model.fit()
        fittedLen = model_fit.fittedvalues.shape[0]
        ar_result[ts.shape[0] - fittedLen:] = model_fit.fittedvalues
        ar_result[:ts.shape[0] - fittedLen] = ts[:ts.shape[0] - fittedLen]
        return ar_result


In [10]:
train_data = np.ones(500)
train_data[20] = 100

test_data = np.ones(500)
test_data[40] = 100

In [11]:
train_data

array([  1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1., 100.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   

In [12]:
test_data

array([  1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1., 100.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   

In [5]:
from pyod.models.loda import LODA

In [13]:
od = LODA(n_bins=10)

In [14]:
od.fit(train_data.reshape(-1, 1))

LODA(contamination=0.1, n_bins=10, n_random_cuts=100)

In [15]:
anomaly_score = od.decision_function(test_data.reshape(-1, 1))

In [16]:
anomaly_score

array([2.00200267e-05, 2.00200267e-05, 2.00200267e-05, 2.00200267e-05,
       2.00200267e-05, 2.00200267e-05, 2.00200267e-05, 2.00200267e-05,
       2.00200267e-05, 2.00200267e-05, 2.00200267e-05, 2.00200267e-05,
       2.00200267e-05, 2.00200267e-05, 2.00200267e-05, 2.00200267e-05,
       2.00200267e-05, 2.00200267e-05, 2.00200267e-05, 2.00200267e-05,
       2.00200267e-05, 2.00200267e-05, 2.00200267e-05, 2.00200267e-05,
       2.00200267e-05, 2.00200267e-05, 2.00200267e-05, 2.00200267e-05,
       2.00200267e-05, 2.00200267e-05, 2.00200267e-05, 2.00200267e-05,
       2.00200267e-05, 2.00200267e-05, 2.00200267e-05, 2.00200267e-05,
       2.00200267e-05, 2.00200267e-05, 2.00200267e-05, 2.00200267e-05,
       6.21460810e-02, 2.00200267e-05, 2.00200267e-05, 2.00200267e-05,
       2.00200267e-05, 2.00200267e-05, 2.00200267e-05, 2.00200267e-05,
       2.00200267e-05, 2.00200267e-05, 2.00200267e-05, 2.00200267e-05,
       2.00200267e-05, 2.00200267e-05, 2.00200267e-05, 2.00200267e-05,
      

In [17]:
test_data

array([  1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1., 100.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   