In [1]:
%load_ext autoreload
%autoreload 2

In [4]:
import os
import pandas as pd
import pickle as pkl
import numpy as np
from common.sliding import BatchSlidingWindow

In [5]:
output_folder = './datasets/SMD/processed'
with open(os.path.join(output_folder, "machine-1-1_test.pkl"), "rb") as fr:
    sample_data = pkl.load(fr)
with open(os.path.join(output_folder, "machine-1-1_test_label.pkl"), "rb") as fr:
    label = pkl.load(fr)
print(sample_data.shape)

(28479, 38)


In [50]:
sample_array = sample_data.T

In [51]:
sliding_window = BatchSlidingWindow(sample_array.shape[1], window_size=100, batch_size=32)

In [52]:
batch = next(iter(sliding_window.get_iterator(sample_array)))

In [54]:
batch.shape

(38, 32, 100)

In [41]:
len(batch)

38

In [43]:
batch[0][0]

array([0.075269, 0.086022, 0.075269, 0.086022, 0.086022, 0.086022,
       0.086022, 0.086022, 0.086022, 0.086022, 0.086022, 0.086022,
       0.086022, 0.086022, 0.086022, 0.086022, 0.075269, 0.086022,
       0.086022, 0.086022, 0.086022, 0.086022, 0.086022, 0.086022,
       0.086022, 0.086022, 0.086022, 0.086022, 0.086022, 0.086022,
       0.086022, 0.086022, 0.086022, 0.086022, 0.086022, 0.086022,
       0.075269, 0.086022, 0.086022, 0.086022, 0.096774, 0.086022,
       0.096774, 0.096774, 0.096774, 0.096774, 0.086022, 0.086022,
       0.086022, 0.096774, 0.096774, 0.096774, 0.096774, 0.096774,
       0.096774, 0.096774, 0.096774, 0.096774, 0.086022, 0.096774,
       0.096774, 0.086022, 0.086022, 0.096774, 0.096774, 0.096774,
       0.096774, 0.086022, 0.096774, 0.096774, 0.096774, 0.096774,
       0.107527, 0.096774, 0.150538, 0.139785, 0.11828 , 0.129032,
       0.129032, 0.139785, 0.129032, 0.139785, 0.150538, 0.139785,
       0.150538, 0.150538, 0.150538, 0.150538, 0.150538, 0.150

In [48]:
batch[1][0]

array([0.065678, 0.080508, 0.064619, 0.048729, 0.051907, 0.085805,
       0.070975, 0.059322, 0.043432, 0.050847, 0.097458, 0.074153,
       0.121822, 0.103814, 0.097458, 0.10911 , 0.070975, 0.076271,
       0.04661 , 0.079449, 0.075212, 0.102754, 0.059322, 0.034958,
       0.087924, 0.067797, 0.036017, 0.067797, 0.059322, 0.042373,
       0.082627, 0.059322, 0.080508, 0.045551, 0.067797, 0.068856,
       0.041314, 0.04661 , 0.190678, 0.129237, 0.147246, 0.098517,
       0.09322 , 0.102754, 0.083686, 0.068856, 0.103814, 0.080508,
       0.075212, 0.077331, 0.049788, 0.099576, 0.104873, 0.070975,
       0.088983, 0.099576, 0.126059, 0.080508, 0.081568, 0.148305,
       0.118644, 0.080508, 0.079449, 0.055085, 0.060381, 0.049788,
       0.068856, 0.042373, 0.038136, 0.043432, 0.034958, 0.072034,
       0.099576, 0.118644, 0.105932, 0.113347, 0.115466, 0.112288,
       0.115466, 0.147246, 0.134534, 0.181144, 0.225636, 0.163136,
       0.133475, 0.1875  , 0.161017, 0.192797, 0.179025, 0.156

In [49]:
sample_array[1, 0:100]

array([0.065678, 0.080508, 0.064619, 0.048729, 0.051907, 0.085805,
       0.070975, 0.059322, 0.043432, 0.050847, 0.097458, 0.074153,
       0.121822, 0.103814, 0.097458, 0.10911 , 0.070975, 0.076271,
       0.04661 , 0.079449, 0.075212, 0.102754, 0.059322, 0.034958,
       0.087924, 0.067797, 0.036017, 0.067797, 0.059322, 0.042373,
       0.082627, 0.059322, 0.080508, 0.045551, 0.067797, 0.068856,
       0.041314, 0.04661 , 0.190678, 0.129237, 0.147246, 0.098517,
       0.09322 , 0.102754, 0.083686, 0.068856, 0.103814, 0.080508,
       0.075212, 0.077331, 0.049788, 0.099576, 0.104873, 0.070975,
       0.088983, 0.099576, 0.126059, 0.080508, 0.081568, 0.148305,
       0.118644, 0.080508, 0.079449, 0.055085, 0.060381, 0.049788,
       0.068856, 0.042373, 0.038136, 0.043432, 0.034958, 0.072034,
       0.099576, 0.118644, 0.105932, 0.113347, 0.115466, 0.112288,
       0.115466, 0.147246, 0.134534, 0.181144, 0.225636, 0.163136,
       0.133475, 0.1875  , 0.161017, 0.192797, 0.179025, 0.156